Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and got FEATURE_TOGGLE_MASTER = false
Starting new HTTP connection (1): 35.233.195.148
Changed FEATURE_TOGGLE_MASTER to true, sleeping 60 seconds to let API restart properly
Finished sleeping
Attempting to add site with payload: {'siteName': '', 'address': '', 'userName': '', 'password': '', 'host': 'http://10.138.0.29:3000', 'rmqConnString': 'amqp://10.138.0.29:5672', 'syncServiceUri': 'http://10.138.0.29:16180', 'title': 'site 10.138.0.29', 'storageUri': 'https://hq.tls.ai/r/35.233.195.148'}
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and got FEATURE_TOGGLE_MASTER = true
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and got FEATURE_TOGGLE_MASTER = false
Starting new HTTP connection (1): 35.233.195.148
Changed FEATURE_TOGGLE_MASTER to true, sleeping 60 seconds to let API restart properly
Finished sleeping
Attempting to add site with payload: {'siteName': '', 'address': '', 'userName': '', 'password': '', 'host': 'http://10.138.0.29:3000', 'rmqConnString': 'amqp://10.138.0.29:5672', 'syncServiceUri': 'http://10.138.0.29:16180', 'title': 'site 10.138.0.29', 'storageUri': 'https://hq.tls.ai/r/35.233.195.148'}
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTPS connection (1): hq-api.tls.ai
Successful logged in and got token
test
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and got FEATURE_TOGGLE_MASTER = false
Starting new HTTP connection (1): 35.233.195.148
Changed FEATURE_TOGGLE_MASTER to true, sleeping 60 seconds to let API restart properly
Finished sleeping
Attempting to add site with payload: {'siteName': '', 'address': '', 'userName': '', 'password': '', 'host': 'http://10.138.0.29:3000', 'rmqConnString': 'amqp://10.138.0.29:5672', 'syncServiceUri': 'http://10.138.0.29:16180', 'title': 'site 10.138.0.29', 'storageUri': 'https://hq.tls.ai/r/35.233.195.148'}
Starting new HTTPS connection (1): hq-api.tls.ai
successfully added site with internal IP 10.138.0.29and external IP 35.233.195.148
Starting new HTTPS connection (1): hq-api.tls.ai
Successful logged in and got token
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and get FEATURE_TOGGLE_MASTER = false
Starting new HTTP connection (1): 35.233.195.148
Changed FEATURE_TOGGLE_MASTER to true, sleeping 60 seconds to let API restart properly
Finished sleeping
successfully added site with internal IP 10.138.0.29and external IP 35.233.195.148
Starting new HTTPS connection (1): hq-api.tls.ai
Successful logged in and got token
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and get FEATURE_TOGGLE_MASTER value = true
Attempting to add site with payload: {'siteName': '', 'address': '', 'userName': '', 'password': '', 'host': 'http://10.138.0.29:3000', 'rmqConnString': 'amqp://10.138.0.29:5672', 'syncServiceUri': 'http://10.138.0.29:16180', 'title': 'site 10.138.0.29', 'storageUri': 'https://hq.tls.ai/r/35.233.195.148'}
Starting new HTTPS connection (1): hq-api.tls.ai
successfully added site with internal IP 10.138.0.29 and external IP 35.233.195.148
Starting new HTTPS connection (1): hq-api.tls.ai
Successful logged in and got token
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and get FEATURE_TOGGLE_MASTER value = false
Starting new HTTP connection (1): 35.233.195.148
Changed FEATURE_TOGGLE_MASTER to true, sleeping 60 seconds to let API restart properly
Finished sleeping
successfully added site with internal IP 10.138.0.29 and external IP 35.233.195.148
Starting new HTTPS connection (1): hq-api.tls.ai
Successful logged in and got token
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and get FEATURE_TOGGLE_MASTER value = true
Attempting to add site with payload: {'siteName': '', 'address': '', 'userName': '', 'password': '', 'host': 'http://10.138.0.29:3000', 'rmqConnString': 'amqp://10.138.0.29:5672', 'syncServiceUri': 'http://10.138.0.29:16180', 'title': 'site 10.138.0.29', 'storageUri': 'https://hq.tls.ai/r/35.233.195.148'}
Starting new HTTPS connection (1): hq-api.tls.ai
successfully added site with internal IP 10.138.0.29 and external IP 35.233.195.148
Starting new HTTPS connection (1): hq-api.tls.ai
Successful logged in and got token
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and get FEATURE_TOGGLE_MASTER value = false
Starting new HTTP connection (1): 35.233.195.148
Changed FEATURE_TOGGLE_MASTER to true, sleeping 60 seconds to let API restart properly
Finished sleeping
successfully added site with internal IP 10.138.0.29 and external IP 35.233.195.148
Starting new HTTPS connection (1): hq-api.tls.ai
Successful logged in and got token
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and get FEATURE_TOGGLE_MASTER value = true
Attempting to add site with payload: {'siteName': '', 'address': '', 'userName': '', 'password': '', 'host': 'http://10.138.0.29:3000', 'rmqConnString': 'amqp://10.138.0.29:5672', 'syncServiceUri': 'http://10.138.0.29:16180', 'title': 'site 10.138.0.29', 'storageUri': 'https://hq.tls.ai/r/35.233.195.148'}
Starting new HTTPS connection (1): hq-api.tls.ai
successfully added site with internal IP 10.138.0.29 and external IP 35.233.195.148
Starting new HTTPS connection (1): hq-api.tls.ai
Successful logged in and got token
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and get FEATURE_TOGGLE_MASTER value = false
Starting new HTTP connection (1): 35.233.195.148
Changed FEATURE_TOGGLE_MASTER to true, sleeping 60 seconds to let API restart properly
Finished sleeping
successfully added site with internal IP 10.138.0.29 and external IP 35.233.195.148
Starting new HTTPS connection (1): hq-api.tls.ai
Successful logged in and got token
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and get FEATURE_TOGGLE_MASTER value = true
Attempting to add site with payload: {'siteName': '', 'address': '', 'userName': '', 'password': '', 'host': 'http://10.138.0.29:3000', 'rmqConnString': 'amqp://10.138.0.29:5672', 'syncServiceUri': 'http://10.138.0.29:16180', 'title': 'site 10.138.0.29', 'storageUri': 'https://hq.tls.ai/r/35.233.195.148'}
Starting new HTTPS connection (1): hq-api.tls.ai
successfully added site with internal IP 10.138.0.29 and external IP 35.233.195.148
Starting new HTTPS connection (1): hq-api.tls.ai
Successful logged in and got token
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and get FEATURE_TOGGLE_MASTER value = false
Starting new HTTP connection (1): 35.233.195.148
Changed FEATURE_TOGGLE_MASTER to true, sleeping 60 seconds to let API restart properly
Finished sleeping
successfully added site with internal IP 10.138.0.29 and external IP 35.233.195.148
Starting new HTTPS connection (1): hq-api.tls.ai
Successful logged in and got token
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and get FEATURE_TOGGLE_MASTER value = true
Attempting to add site with payload: {'siteName': '', 'address': '', 'userName': '', 'password': '', 'host': 'http://10.138.0.29:3000', 'rmqConnString': 'amqp://10.138.0.29:5672', 'syncServiceUri': 'http://10.138.0.29:16180', 'title': 'site 10.138.0.29', 'storageUri': 'https://hq.tls.ai/r/35.233.195.148'}
Starting new HTTPS connection (1): hq-api.tls.ai
successfully added site with internal IP 10.138.0.29 and external IP 35.233.195.148
Starting new HTTPS connection (1): hq-api.tls.ai
Successful logged in and got token
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and get FEATURE_TOGGLE_MASTER value = false
Starting new HTTP connection (1): 35.233.195.148
Changed FEATURE_TOGGLE_MASTER to true, sleeping 60 seconds to let API restart properly
Finished sleeping
Attempting to add site with payload: {'siteName': '', 'address': '', 'userName': '', 'password': '', 'host': 'http://10.138.0.29:3000', 'rmqConnString': 'amqp://10.138.0.29:5672', 'syncServiceUri': 'http://10.138.0.29:16180', 'title': 'site 10.138.0.29', 'storageUri': 'https://hq.tls.ai/r/35.233.195.148'}
Starting new HTTPS connection (1): hq-api.tls.ai
successfully added site with internal IP 10.138.0.29 and external IP 35.233.195.148
Starting new HTTPS connection (1): hq-api.tls.ai
Successful logged in and got token
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and get FEATURE_TOGGLE_MASTER value = false
Starting new HTTP connection (1): 35.233.195.148
Changed FEATURE_TOGGLE_MASTER to true, sleeping 60 seconds to let API restart properly
Finished sleeping
Attempting to add site with payload: {'siteName': '', 'address': '', 'userName': '', 'password': '', 'host': 'http://10.138.0.29:3000', 'rmqConnString': 'amqp://10.138.0.29:5672', 'syncServiceUri': 'http://10.138.0.29:16180', 'title': 'site 10.138.0.29', 'storageUri': 'https://hq.tls.ai/r/35.233.195.148'}
Starting new HTTPS connection (1): hq-api.tls.ai
successfully added site with internal IP 10.138.0.29 and external IP 35.233.195.148
Starting new HTTPS connection (1): hq-api.tls.ai
Successful logged in and got token
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and get FEATURE_TOGGLE_MASTER value = false
Starting new HTTP connection (1): 35.233.195.148
Changed FEATURE_TOGGLE_MASTER to true, sleeping 60 seconds to let API restart properly
Finished sleeping
Attempting to add site with payload: {'siteName': '', 'address': '', 'userName': '', 'password': '', 'host': 'http://10.138.0.29:3000', 'rmqConnString': 'amqp://10.138.0.29:5672', 'syncServiceUri': 'http://10.138.0.29:16180', 'title': 'site 10.138.0.29', 'storageUri': 'https://hq.tls.ai/r/35.233.195.148'}
Starting new HTTPS connection (1): hq-api.tls.ai
successfully added site with internal IP 10.138.0.29 and external IP 35.233.195.148
Starting new HTTPS connection (1): hq-api.tls.ai
Successful logged in and got token
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and get FEATURE_TOGGLE_MASTER value = false
Starting new HTTP connection (1): 35.233.195.148
Changed FEATURE_TOGGLE_MASTER to true, sleeping 60 seconds to let API restart properly
Finished sleeping
Attempting to add site with payload: {'siteName': '', 'address': '', 'userName': '', 'password': '', 'host': 'http://10.138.0.29:3000', 'rmqConnString': 'amqp://10.138.0.29:5672', 'syncServiceUri': 'http://10.138.0.29:16180', 'title': 'site 10.138.0.29', 'storageUri': 'https://hq.tls.ai/r/35.233.195.148'}
Starting new HTTPS connection (1): hq-api.tls.ai
successfully added site with internal IP 10.138.0.29 and external IP 35.233.195.148
Starting new HTTPS connection (1): hq-api.tls.ai
Successful logged in and got token
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and get FEATURE_TOGGLE_MASTER value = false
Starting new HTTP connection (1): 35.233.195.148
Changed FEATURE_TOGGLE_MASTER to true, sleeping 60 seconds to let API restart properly
Finished sleeping
Attempting to add site with payload: {'siteName': '', 'address': '', 'userName': '', 'password': '', 'host': 'http://10.138.0.29:3000', 'rmqConnString': 'amqp://10.138.0.29:5672', 'syncServiceUri': 'http://10.138.0.29:16180', 'title': 'site 10.138.0.29', 'storageUri': 'https://hq.tls.ai/r/35.233.195.148'}
Starting new HTTPS connection (1): hq-api.tls.ai
successfully added site with internal IP 10.138.0.29 and external IP 35.233.195.148
Starting new HTTPS connection (1): hq-api.tls.ai
Successful logged in and got token
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and get FEATURE_TOGGLE_MASTER value = false
Starting new HTTP connection (1): 35.233.195.148
Changed FEATURE_TOGGLE_MASTER to true, sleeping 60 seconds to let API restart properly
Finished sleeping
Attempting to add site with payload: {'siteName': '', 'address': '', 'userName': '', 'password': '', 'host': 'http://10.138.0.29:3000', 'rmqConnString': 'amqp://10.138.0.29:5672', 'syncServiceUri': 'http://10.138.0.29:16180', 'title': 'site 10.138.0.29', 'storageUri': 'https://hq.tls.ai/r/35.233.195.148'}
Starting new HTTPS connection (1): hq-api.tls.ai
successfully added site with internal IP 10.138.0.29 and external IP 35.233.195.148
Starting new HTTPS connection (1): hq-api.tls.ai
Successful logged in and got token
Starting new HTTP connection (1): 35.233.195.148
Connect to consul at 35.233.195.148 and get FEATURE_TOGGLE_MASTER value = false
Starting new HTTP connection (1): 35.233.195.148
Changed FEATURE_TOGGLE_MASTER to true, sleeping 60 seconds to let API restart properly
Finished sleeping
Attempting to add site with payload: {'siteName': '', 'address': '', 'userName': '', 'password': '', 'host': 'http://10.138.0.29:3000', 'rmqConnString': 'amqp://10.138.0.29:5672', 'syncServiceUri': 'http://10.138.0.29:16180', 'title': 'site 10.138.0.29', 'storageUri': 'https://hq.tls.ai/r/35.233.195.148'}
Starting new HTTPS connection (1): hq-api.tls.ai
successfully added site with internal IP 10.138.0.29 and external IP 35.233.195.148
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTPS connection (1): hq-api.tls.ai
Starting new HTTP connection (1): 35.195.7.50
Connect to consul at 35.195.7.50 and get FEATURE_TOGGLE_MASTER value = false
Starting new HTTP connection (1): 35.195.7.50
Changed FEATURE_TOGGLE_MASTER to true, sleeping 60 seconds to let API restart properly
Finished sleeping
Initiated config with {'site_internal_ip': 'a', 'site_extarnel_ip': 'a', 'hq_api_url': 'hq-api.tls.ai', 'hq_url': 'hq.tls.ai', 'consul_ip': 'a'}
Current running VM's b'/home/qa-machine/automation-helm\n'
Initiated config with {'site_internal_ip': 'a', 'site_extarnel_ip': 'a', 'hq_api_url': 'hq-api.tls.ai', 'hq_url': 'hq.tls.ai', 'consul_ip': 'a'}
Current running VM's b' Id    Name                           State\n----------------------------------------------------\n\n'
Initiated config with {'site_internal_ip': 'a', 'site_extarnel_ip': 'a', 'hq_api_url': 'hq-api.tls.ai', 'hq_url': 'hq.tls.ai', 'consul_ip': 'a'}
Current running VM's b' Id    Name                           State\n----------------------------------------------------\n\n'
Initiated config with {'site_internal_ip': 'a', 'site_extarnel_ip': 'a', 'hq_api_url': 'hq-api.tls.ai', 'hq_url': 'hq.tls.ai', 'consul_ip': 'a'}
Initiated config with {'site_internal_ip': '192.168.122.41', 'site_extarnel_ip': '192.168.122.41', 'hq_api_url': 'hq-api.tls.ai', 'hq_url': 'hq.tls.ai', 'consul_ip': '192.168.122.41'}
Recei:qved the following args Namespace(add_multiple_subjects=False, add_single_subject=False, env='vm')
Initiated config with {'site_internal_ip': '192.168.122.41', 'site_extarnel_ip': '192.168.122.41', 'hq_api_url': 'hq-api.tls.ai', 'hq_url': 'hq.tls.ai', 'consul_ip': '192.168.122.41'}
Received the following args Namespace(add_multiple_subjects=False, add_single_subject=False, env='vm')
Initiated config with {'site_internal_ip': '192.168.122.41', 'site_extarnel_ip': '192.168.122.41', 'hq_api_url': 'hq-api.tls.ai', 'hq_url': 'hq.tls.ai', 'consul_ip': '192.168.122.41'}
Received the following args Namespace(add_multiple_subjects=False, add_single_subject=False, env='vm')
Initiated config with {'site_internal_ip': '192.168.122.41', 'site_extarnel_ip': '192.168.122.41', 'hq_api_url': 'hq-api.tls.ai', 'hq_url': 'hq.tls.ai', 'consul_ip': '192.168.122.41'}
Received the following args: Namespace(add_multiple_subjects=False, add_single_subject=False, env='vm')
Initiated config with: {'site_internal_ip': '192.168.122.41', 'site_extarnel_ip': '192.168.122.41', 'hq_api_url': 'hq-api.tls.ai', 'hq_url': 'hq.tls.ai', 'consul_ip': '192.168.122.41'}
Received the following args: Namespace(add_multiple_subjects=False, add_single_subject=False, env='vm')
Initiated config with: {'site_internal_ip': '192.168.122.41', 'site_extarnel_ip': '192.168.122.41', 'hq_api_url': 'hq-api.tls.ai', 'hq_url': 'hq.tls.ai', 'consul_ip': '192.168.122.41'}
Received the following args: Namespace(add_multiple_subjects=False, add_single_subject=False, env='vm')
Attempting to Mongo on 192.168.122.41
Attempting to Mongo on 192.168.122.41
Attempting to start all hq nodes
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=Name%3A+aharon%2A&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=Name%3A+aharon&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=Name%3A+aharon&alt=json
URL being requested: POST https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1/stop?alt=json
URL being requested: POST https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1/stop?alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=Labels%3Aauto%3Atest&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=Labels%3Aauto%3Dtest&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=Labels.auto%3Dtest&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=Labels.env%3Ddev&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.env%3Ddev&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto%3Dtest&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=%28%27Labels%3Aauto%3Dtest%27%2C%29&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=Labels%3Aauto%3Dtest&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=Labels%3A&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=Name%3Aaharon%2A&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=%28Name%3Aaharon%2A%29&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=%28%29&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=label.auto%3Dtest&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=label.auto%3Dtest&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=label.auto&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=label.auto%3Dtest&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=label.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test+and+status+eq+RUNNING&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test+and+status+eq+RUNNING&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test+&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test+&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test+&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test+&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: POST https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1/start?alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
Starting tests with Namespace(add_multiple_subjects=None, add_single_subject=None, config='config/config_example.json', connect_to_hq_mongo=None, delete_all_subjects=None, env='vm', recognition_event=None, remove_site=None, run_site_tasks=None)
Received config: {'hq_pass': '',
 'hq_user': '',
 'mongo_service_url': 'mongodb.replicaset-0.mongodb-replicaset,mongodb.replicaset-1.mongodb-replicaset,mongodb.replicaset-2.mongodb-replicaset',
 'site_ip': '',
 'site_pass': ''}
Received config: [{'hq_api_url': 'hq-api.tls.ai',
  'hq_url': 'hq.tls.ai',
  'site_consul_ip': '192.168.122.41',
  'site_extarnel_ip': '192.168.122.41',
  'site_internal_ip': '192.168.122.41',
  'ssh': {'password': '', 'pem_path': '', 'username': ''}}]
file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/compute/v1/rest
Setup the machine_mgmt class <vm_management.GcpInstanceMgmt object at 0x7fe784d4ff28>
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
Successfully iteration: 0 Failed iteration: 0
Starting tests with Namespace(add_multiple_subjects=None, add_single_subject=None, config='config/config_example.json', connect_to_hq_mongo=None, delete_all_subjects=None, env='vm', recognition_event=None, remove_site=None, run_site_tasks=None)
Received config: {'hq_pass': '',
 'hq_user': '',
 'mongo_service_url': 'mongodb.replicaset-0.mongodb-replicaset,mongodb.replicaset-1.mongodb-replicaset,mongodb.replicaset-2.mongodb-replicaset',
 'site_ip': '',
 'site_pass': ''}
Received config: [{'hq_api_url': 'hq-api.tls.ai',
  'hq_url': 'hq.tls.ai',
  'site_consul_ip': '192.168.122.41',
  'site_extarnel_ip': '192.168.122.41',
  'site_internal_ip': '192.168.122.41',
  'ssh': {'password': '', 'pem_path': '', 'username': ''}}]
file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/compute/v1/rest
Setup the machine_mgmt class <vm_management.GcpInstanceMgmt object at 0x7f21020c0fd0>
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
Successfully iteration: 0 Failed iteration: 0
Starting tests with Namespace(add_multiple_subjects=None, add_single_subject=None, config='config/config_example.json', connect_to_hq_mongo=None, delete_all_subjects=None, env='vm', recognition_event=None, remove_site=None, run_site_tasks=None)
Received config: {'hq_pass': '',
 'hq_user': '',
 'mongo_service_url': 'mongodb.replicaset-0.mongodb-replicaset,mongodb.replicaset-1.mongodb-replicaset,mongodb.replicaset-2.mongodb-replicaset',
 'site_ip': '',
 'site_pass': ''}
Received config: [{'hq_api_url': 'hq-api.tls.ai',
  'hq_url': 'hq.tls.ai',
  'site_consul_ip': '192.168.122.41',
  'site_extarnel_ip': '192.168.122.41',
  'site_internal_ip': '192.168.122.41',
  'ssh': {'password': '', 'pem_path': '', 'username': ''}}]
file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/compute/v1/rest
Setup the machine_mgmt class <vm_management.GcpInstanceMgmt object at 0x7f91e7c77fd0>
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
Successfully iteration: 0 Failed iteration: 0
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
Checked that 3 HQ nodes are started, stopping one of them
URL being requested: POST https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1/stop?alt=json
Stopping aharon-hq-ha-d-us-west1-b-1
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1?alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1?alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1?alt=json
aharon-hq-ha-d-us-west1-b-1 is still up even though it should have stopped sleeping for another 10 seconds
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1?alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1?alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1?alt=json
aharon-hq-ha-d-us-west1-b-1 is still up even though it should have stopped sleeping for another 10 seconds
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1?alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1?alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1?alt=json
aharon-hq-ha-d-us-west1-b-1 is still up even though it should have stopped sleeping for another 10 seconds
Starting tests with Namespace(add_multiple_subjects=None, add_single_subject=None, config='config/config_example.json', connect_to_hq_mongo=None, delete_all_subjects=None, env='vm', recognition_event=None, remove_site=None, run_site_tasks=None)
Received config: {'hq_pass': '',
 'hq_user': '',
 'mongo_service_url': 'mongodb.replicaset-0.mongodb-replicaset,mongodb.replicaset-1.mongodb-replicaset,mongodb.replicaset-2.mongodb-replicaset',
 'site_ip': '',
 'site_pass': ''}
Received config: [{'hq_api_url': 'hq-api.tls.ai',
  'hq_url': 'hq.tls.ai',
  'site_consul_ip': '192.168.122.41',
  'site_extarnel_ip': '192.168.122.41',
  'site_internal_ip': '192.168.122.41',
  'ssh': {'password': '', 'pem_path': '', 'username': ''}}]
file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/compute/v1/rest
Setup the machine_mgmt class <vm_management.GcpInstanceMgmt object at 0x7fb2cf684ef0>
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: POST https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1/start?alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
Attempting to start aharon-hq-ha-d-us-west1-b-1 in order to get back to 3 hq nodes being up for tha test to start properly
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: POST https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1/start?alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
Attempting to start aharon-hq-ha-d-us-west1-b-1 in order to get back to 3 hq nodes being up for tha test to start properly
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
Successfully iteration: 0 Failed iteration: 0
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
Starting tests with Namespace(add_multiple_subjects=None, add_single_subject=None, config='config/config_example.json', connect_to_hq_mongo=None, delete_all_subjects=None, env='vm', recognition_event=None, remove_site=None, run_site_tasks=None)
Received config: {'hq_pass': 'M2Q1MDUzYjYyOGM4N2JhN2JmYjM1MTMz',
 'hq_user': 'root',
 'mongo_service_url': 'mongodb.replicaset-0.mongodb-replicaset,mongodb.replicaset-1.mongodb-replicaset,mongodb.replicaset-2.mongodb-replicaset',
 'site_ip': '',
 'site_pass': ''}
Received config: [{'hq_api_url': 'hq-api.tls.ai',
  'hq_url': 'hq.tls.ai',
  'site_consul_ip': '192.168.122.41',
  'site_extarnel_ip': '192.168.122.41',
  'site_internal_ip': '192.168.122.41',
  'ssh': {'password': '', 'pem_path': '', 'username': ''}}]
file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/compute/v1/rest
Setup the machine_mgmt class <vm_management.GcpInstanceMgmt object at 0x7f8d9d7bef28>
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
Successfully iteration: 0 Failed iteration: 0
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
Checked that 3 HQ nodes are started, stopping one of them
URL being requested: POST https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1/stop?alt=json
Stopping aharon-hq-ha-d-us-west1-b-1
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1?alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1?alt=json
Sleeping after stopping node for 600 seconds
Starting tests with Namespace(add_multiple_subjects=None, add_single_subject=None, config='config/config_example.json', connect_to_hq_mongo=None, delete_all_subjects=None, env='vm', recognition_event=None, remove_site=None, run_site_tasks=None)
Received config: {'hq_pass': 'M2Q1MDUzYjYyOGM4N2JhN2JmYjM1MTMz',
 'hq_user': 'root',
 'mongo_service_url': 'mongodb.replicaset-0.mongodb-replicaset,mongodb.replicaset-1.mongodb-replicaset,mongodb.replicaset-2.mongodb-replicaset',
 'site_ip': '',
 'site_pass': ''}
Received config: [{'hq_api_url': 'hq-api.tls.ai',
  'hq_url': 'hq.tls.ai',
  'site_consul_ip': '192.168.122.41',
  'site_extarnel_ip': '192.168.122.41',
  'site_internal_ip': '192.168.122.41',
  'ssh': {'password': '', 'pem_path': '', 'username': ''}}]
file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/compute/v1/rest
Setup the machine_mgmt class <vm_management.GcpInstanceMgmt object at 0x7f2aa0917fd0>
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: POST https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1/start?alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
Attempting to start aharon-hq-ha-d-us-west1-b-1 in order to get back to 3 hq nodes being up for tha test to start properly
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: POST https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1/start?alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
Attempting to start aharon-hq-ha-d-us-west1-b-1 in order to get back to 3 hq nodes being up for tha test to start properly
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
Successfully iteration: 0 Failed iteration: 0
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
Sleeping after stopping node for 300 seconds
Finished sleeping 300 seconds
Starting tests with Namespace(add_multiple_subjects=None, add_single_subject=None, config='config/config_example.json', connect_to_hq_mongo=None, delete_all_subjects=None, env='vm', recognition_event=None, remove_site=None, run_site_tasks=None)
Received config: {'hq_pass': 'M2Q1MDUzYjYyOGM4N2JhN2JmYjM1MTMz',
 'hq_user': 'root',
 'mongo_service_url': 'mongodb.replicaset-0.mongodb-replicaset,mongodb.replicaset-1.mongodb-replicaset,mongodb.replicaset-2.mongodb-replicaset',
 'site_ip': '',
 'site_pass': ''}
Received config: [{'hq_api_url': 'hq-api.tls.ai',
  'hq_url': 'hq.tls.ai',
  'site_consul_ip': '192.168.122.41',
  'site_extarnel_ip': '192.168.122.41',
  'site_internal_ip': '192.168.122.41',
  'ssh': {'password': '', 'pem_path': '', 'username': ''}}]
file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/home/qa-machine/.local/lib/python3.6/site-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
URL being requested: GET https://www.googleapis.com/discovery/v1/apis/compute/v1/rest
Setup the machine_mgmt class <vm_management.GcpInstanceMgmt object at 0x7ff25efaef28>
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
Successfully iteration: 0 Failed iteration: 0
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances?filter=labels.auto+eq+test&alt=json
Checked that 3 HQ nodes are started, stopping one of them
URL being requested: POST https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1/stop?alt=json
Stopping aharon-hq-ha-d-us-west1-b-1
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1?alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1?alt=json
URL being requested: GET https://compute.googleapis.com/compute/v1/projects/anyvision-training/zones/us-west1-b/instances/aharon-hq-ha-d-us-west1-b-1?alt=json
Sleeping after stopping node for 300 seconds
Finished sleeping 300 seconds
